name: ideasamaapp
description: "Fast offline-first idea notes app"
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3+1
  share_plus: ^10.1.4
  http: ^1.2.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1
  sqflite_common_ffi_web: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ideasamaapp_logo.svg
