name: Android CI (APK & AAB)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        working-directory: idea_app
        run: flutter pub get

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses || true

      - name: Build APK (release, unsigned)
        working-directory: idea_app
        run: flutter build apk --release --target-platform android-arm64

      - name: Build AAB (release, unsigned)
        working-directory: idea_app
        run: flutter build appbundle --release --target-platform android-arm64

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: idea_app/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: idea_app/build/app/outputs/bundle/release/app-release.aab