name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to release (e.g., v2025.09.26-2109)'
        required: true
        default: ''

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_type == 'tag' && github.ref_name || inputs.tag }}
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || inputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            Changes in this release:
            - Note editor: move ref.listen to build to avoid mis-lifecycle usage
            - Dispose text controllers to prevent leaks
            - Better error handling (async + UI)
            - UI polish for AI suggestions panel
            - DevTools config and run setup

            Housekeeping:
            - Add CI workflow for Flutter analyze/test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}